=== GeorgeJuarez660/GeoStore/src/main/resources/org/xml/rules/formatReceiptTD.dtd
<!--Regole di mappatura (di schematizzazione)-->
<!ELEMENT Scontrino (Intestazione, Corpo, PiedeDataOrdini, PiedeTotale, Didascalia)>
<!ELEMENT Intestazione (nomeNegozio, via) >
<!ELEMENT nomeNegozio (#PCDATA) >
<!ELEMENT via (#PCDATA) >
<!ELEMENT Corpo (TitoloTabella, CorpoTabella)>
<!ELEMENT PiedeDataOrdini (colonnaPDT, colonnaPDC)>
<!ELEMENT PiedeTotale (colonnaPT, colonnaPC)>
<!ELEMENT Didascalia (DidascaliaTitolo, DidascaliaCorpo)>
<!ELEMENT TitoloTabella (colonnaT1, colonnaT2)>
<!ELEMENT CorpoTabella (colonnaC1, colonnaC2)>
<!ELEMENT colonnaT1 (#PCDATA) >
<!ELEMENT colonnaT2 (#PCDATA) >
<!ELEMENT colonnaC1 (#PCDATA) >
<!ELEMENT colonnaC2 (#PCDATA) >
<!ELEMENT colonnaPDT (#PCDATA) >
<!ELEMENT colonnaPDC (#PCDATA) >
<!ELEMENT colonnaPT (#PCDATA) >
<!ELEMENT colonnaPC (#PCDATA) >
<!ELEMENT DidascaliaTitolo (colonnaDT, colonnaNT)>
<!ELEMENT DidascaliaCorpo (colonnaDC, colonnaNC)>
<!ELEMENT colonnaDT (#PCDATA) >
<!ELEMENT colonnaNT (#PCDATA) >
<!ELEMENT colonnaDC (#PCDATA) >
<!ELEMENT colonnaNC (#PCDATA) >

=== GeorgeJuarez660/GeoStore/GeostoreFX/target/classes/org/xml/receiptTD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--Scontrino GeoStore per l'ordinazione prodotto-->
<!DOCTYPE Scontrino SYSTEM "formatReceiptTD.dtd">
<?xml-stylesheet type="text/xsl" href="styleReceiptTD.xsl" ?>
<Scontrino>
    <Intestazione>
        <nomeNegozio>Negozio virtuale GeoStore</nomeNegozio>
        <via>Sede virtuale</via>
    </Intestazione>
    <Corpo>
        <TitoloTabella>
            <colonnaT1>PRODOTTO</colonnaT1>
            <colonnaT2>PREZZO (C)</colonnaT2>
        </TitoloTabella>
        <CorpoTabella>
            <colonnaC1>xxPRODUCTxx</colonnaC1>
            <colonnaC2>xxPRICExx</colonnaC2>
        </CorpoTabella>
    </Corpo>
    <PiedeDataOrdini>
        <colonnaPDT>DATA ORDINI</colonnaPDT>
        <colonnaPDC>xxORDERSDATExx</colonnaPDC>
    </PiedeDataOrdini>
    <PiedeTotale>
        <colonnaPT>TOTALE</colonnaPT>
        <colonnaPC>xxTOTALPRICExx</colonnaPC>
    </PiedeTotale>
    <Didascalia>
        <DidascaliaTitolo>
            <colonnaDT>ID Documento:</colonnaDT>
            <colonnaNT>Cliente</colonnaNT>
        </DidascaliaTitolo>
        <DidascaliaCorpo>
            <colonnaDC>xxCHMxx</colonnaDC>
            <colonnaNC>xxUSERxx</colonnaNC>
        </DidascaliaCorpo>
    </Didascalia>

</Scontrino>

=== GeorgeJuarez660/GeoStore/src/main/resources/org/xml/receiptTD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--Scontrino GeoStore per l'ordinazione prodotto-->
<!DOCTYPE Scontrino SYSTEM
        "C:\Users\giorg\OneDrive\Desktop\App\G&P\Programming\Java\GeostoreFX\src\main\resources\org\xml\rules\formatReceiptTD.dtd">
<?xml-stylesheet type="text/xsl" href="stylesheets/styleReceiptTD.xsl" ?>
<Scontrino>
    <Intestazione>
        <nomeNegozio>Negozio virtuale GeoStore</nomeNegozio>
        <via>Sede virtuale</via>
    </Intestazione>
    <Corpo>
        <TitoloTabella>
            <colonnaT1>PRODOTTO</colonnaT1>
            <colonnaT2>PREZZO (C)</colonnaT2>
        </TitoloTabella>
        <CorpoTabella>
            <colonnaC1>xxPRODUCTxx</colonnaC1>
            <colonnaC2>xxPRICExx</colonnaC2>
        </CorpoTabella>
    </Corpo>
    <PiedeDataOrdini>
        <colonnaPDT>DATA ORDINI</colonnaPDT>
        <colonnaPDC>xxORDERSDATExx</colonnaPDC>
    </PiedeDataOrdini>
    <PiedeTotale>
        <colonnaPT>TOTALE</colonnaPT>
        <colonnaPC>xxTOTALPRICExx</colonnaPC>
    </PiedeTotale>
    <Didascalia>
        <DidascaliaTitolo>
            <colonnaDT>ID Documento:</colonnaDT>
            <colonnaNT>Cliente</colonnaNT>
        </DidascaliaTitolo>
        <DidascaliaCorpo>
            <colonnaDC>xxCHMxx</colonnaDC>
            <colonnaNC>xxUSERxx</colonnaNC>
        </DidascaliaCorpo>
    </Didascalia>

</Scontrino>
